---
title: "Plotting correlation between values."
author: "Edwin van Leeuwen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The mcmcsample package extends ggplot2 to make it easier to plot the correlation between the parameters in your mcmc samples.

```{r}
library(data.table)
param1 <- rnorm( 100, 0, 1 )
param2 <- sapply(param1, function(x) x^2 + rnorm( 1, 0, 1 ) )
# Make sure to add a sample.id column
samples <- data.table( data.frame( list("sample.id"=seq(1,length(param1)), "param1"=param1, "param2"=param2) ) )
```

```{r}
library(mcmcsample)
library(ggplot2)
long.samples <- melt(samples,measure.vars=c("param1","param2"),id.vars = c("sample.id"))
ggs <- gg.correlation(long.samples, "value", "variable")
```

Points that fall outside the credibility interval

```{r}
library(mcmcsample)
library(ggplot2)
smpls <- samples
smpls$ci <- inside.ci(samples,0.8, method="chull")
long.samples <- melt(smpls,measure.vars=c("param1","param2"),id.vars = c("sample.id","ci"))
ggs <- gg.correlation(long.samples, "value", "variable", colour="ci")
```